apiVersion: v1
kind: Namespace
metadata:
  name: kafka-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: kafka-ns
data:
  default.topic.partitions: '10'
  default.topic.replication.factor: '1'
  bootstrap.servers: "173.39.62.80:9092"

---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
    kafka.eventing.knative.dev/external.topic: kn.commit.start
  name: kb-commit
  namespace: kafka-ns
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: kafka-ns
